import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding MealMind database...');

  // ── 1. Demo User ──────────────────────────────────────────────
  const passwordHash = await bcrypt.hash('Demo@1234', 10);
  const user = await prisma.user.upsert({
    where: { email: 'demo@mealmind.vn' },
    update: {},
    create: {
      email: 'demo@mealmind.vn',
      name: 'Lê MealMind',
      passwordHash,
      subscriptionTier: 'free',
      onboardingCompleted: true,
    },
  });
  console.log('  ✅ User:', user.email);

  // ── 1b. Admin User ──────────────────────────────────────────
  const adminHash = await bcrypt.hash('Admin@1234', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@mealmind.vn' },
    update: {},
    create: {
      email: 'admin@mealmind.vn',
      name: 'Admin MealMind',
      passwordHash: adminHash,
      subscriptionTier: 'pro',
      onboardingCompleted: true,
    },
  });
  console.log('  ✅ Admin:', admin.email);

  // ── 2. Taste Profile ──────────────────────────────────────────
  const profile = await prisma.tasteProfile.upsert({
    where: { id: user.id },      // will fail on first run → create
    update: {},
    create: {
      userId: user.id,
      profileName: 'Cá nhân',
      isPrimary: true,
      regions: ['south', 'north'],
      spiceLevel: 3,
      sweetLevel: 4,
      saltLevel: 3,
      dietType: 'normal',
      maxCookTime: 'thirty_to_60',
      familySize: 4,
    },
  }).catch(async () => {
    // upsert by id won't work on first run - create fresh
    return prisma.tasteProfile.create({
      data: {
        userId: user.id,
        profileName: 'Cá nhân',
        isPrimary: true,
        regions: ['south', 'north'],
        spiceLevel: 3,
        sweetLevel: 4,
        saltLevel: 3,
        dietType: 'normal',
        maxCookTime: 'thirty_to_60',
        familySize: 4,
      },
    });
  });
  console.log('  ✅ Taste profile:', profile.profileName);

  // ── 3. Ingredients ────────────────────────────────────────────
  const ingredientData = [
    { name: 'Bánh phở tươi', nameAscii: 'banh pho tuoi', category: 'grain' as const },
    { name: 'Thịt bò nạm', nameAscii: 'thit bo nam', category: 'protein' as const },
    { name: 'Xương ống bò', nameAscii: 'xuong ong bo', category: 'protein' as const },
    { name: 'Hành tây', nameAscii: 'hanh tay', category: 'vegetable' as const },
    { name: 'Gừng', nameAscii: 'gung', category: 'seasoning' as const },
    { name: 'Nước mắm', nameAscii: 'nuoc mam', category: 'seasoning' as const },
    { name: 'Đường phèn', nameAscii: 'duong phen', category: 'seasoning' as const },
    { name: 'Muối', nameAscii: 'muoi', category: 'seasoning' as const },
    { name: 'Hành lá', nameAscii: 'hanh la', category: 'vegetable' as const },
    { name: 'Giá đỗ', nameAscii: 'gia do', category: 'vegetable' as const },
    { name: 'Rau thơm', nameAscii: 'rau thom', category: 'vegetable' as const },
    { name: 'Chanh', nameAscii: 'chanh', category: 'fruit' as const },
    { name: 'Sườn heo', nameAscii: 'suon heo', category: 'protein' as const },
    { name: 'Gạo tấm', nameAscii: 'gao tam', category: 'grain' as const },
    { name: 'Mỡ hành', nameAscii: 'mo hanh', category: 'seasoning' as const },
    { name: 'Bì heo', nameAscii: 'bi heo', category: 'protein' as const },
    { name: 'Trứng ốp la', nameAscii: 'trung op la', category: 'protein' as const },
    { name: 'Đồ chua', nameAscii: 'do chua', category: 'vegetable' as const },
    { name: 'Bún tươi', nameAscii: 'bun tuoi', category: 'grain' as const },
    { name: 'Thịt ba chỉ', nameAscii: 'thit ba chi', category: 'protein' as const },
    { name: 'Chả cua', nameAscii: 'cha cua', category: 'protein' as const },
    { name: 'Mắm ruốc', nameAscii: 'mam ruoc', category: 'seasoning' as const },
    { name: 'Sả', nameAscii: 'sa', category: 'seasoning' as const },
    { name: 'Ớt', nameAscii: 'ot', category: 'seasoning' as const },
    { name: 'Bánh mì', nameAscii: 'banh mi', category: 'grain' as const },
    { name: 'Paté', nameAscii: 'pate', category: 'protein' as const },
    { name: 'Dưa leo', nameAscii: 'dua leo', category: 'vegetable' as const },
    { name: 'Ngò', nameAscii: 'ngo', category: 'vegetable' as const },
    { name: 'Bánh tráng', nameAscii: 'banh trang', category: 'grain' as const },
    { name: 'Tôm', nameAscii: 'tom', category: 'protein' as const, allergenTags: ['shellfish'] },
    { name: 'Bún', nameAscii: 'bun', category: 'grain' as const },
    { name: 'Rau sống', nameAscii: 'rau song', category: 'vegetable' as const },
    { name: 'Tương ớt', nameAscii: 'tuong ot', category: 'seasoning' as const },
    { name: 'Tỏi', nameAscii: 'toi', category: 'seasoning' as const },
    { name: 'Tiêu', nameAscii: 'tieu', category: 'seasoning' as const },
    { name: 'Dầu ăn', nameAscii: 'dau an', category: 'oil' as const },
    { name: 'Bột ngọt', nameAscii: 'bot ngot', category: 'seasoning' as const },
    { name: 'Đường', nameAscii: 'duong', category: 'seasoning' as const },
    { name: 'Mì Quảng', nameAscii: 'mi quang', category: 'grain' as const },
    { name: 'Thịt gà', nameAscii: 'thit ga', category: 'protein' as const },
    { name: 'Tôm sú', nameAscii: 'tom su', category: 'protein' as const, allergenTags: ['shellfish'] },
    { name: 'Đậu phộng', nameAscii: 'dau phong', category: 'other' as const, allergenTags: ['peanuts'] },
    { name: 'Nghệ', nameAscii: 'nghe', category: 'seasoning' as const },
    { name: 'Cơm trắng', nameAscii: 'com trang', category: 'grain' as const },
    { name: 'Cá kho', nameAscii: 'ca kho', category: 'protein' as const, allergenTags: ['fish'] },
    { name: 'Canh chua', nameAscii: 'canh chua', category: 'other' as const },
    { name: 'Me', nameAscii: 'me', category: 'fruit' as const },
    { name: 'Cà chua', nameAscii: 'ca chua', category: 'vegetable' as const },
    { name: 'Thơm (dứa)', nameAscii: 'thom dua', category: 'fruit' as const },
    { name: 'Đậu bắp', nameAscii: 'dau bap', category: 'vegetable' as const },
    { name: 'Bạc hà', nameAscii: 'bac ha', category: 'vegetable' as const },
    { name: 'Thịt heo xay', nameAscii: 'thit heo xay', category: 'protein' as const },
    { name: 'Khổ qua', nameAscii: 'kho qua', category: 'vegetable' as const },
    { name: 'Nấm mèo', nameAscii: 'nam meo', category: 'vegetable' as const },
    { name: 'Miến', nameAscii: 'mien', category: 'grain' as const },
    { name: 'Ớt chuông', nameAscii: 'ot chuong', category: 'vegetable' as const },
    { name: 'Bột bánh xèo', nameAscii: 'bot banh xeo', category: 'grain' as const },
    { name: 'Thịt đùi gà', nameAscii: 'thit dui ga', category: 'protein' as const },
    { name: 'Mắm tôm', nameAscii: 'mam tom', category: 'seasoning' as const },
    { name: 'Đậu hũ non', nameAscii: 'dau hu non', category: 'protein' as const, allergenTags: ['soy'] },
    { name: 'Đậu hũ', nameAscii: 'dau hu', category: 'protein' as const, allergenTags: ['soy'] },
    { name: 'Chả cốm', nameAscii: 'cha com', category: 'protein' as const },
    { name: 'Bánh canh', nameAscii: 'banh canh', category: 'grain' as const },
    { name: 'Tôm khô', nameAscii: 'tom kho', category: 'protein' as const, allergenTags: ['shellfish'] },
    { name: 'Thịt cua', nameAscii: 'thit cua', category: 'protein' as const, allergenTags: ['shellfish'] },
    { name: 'Hủ tiếu', nameAscii: 'hu tieu', category: 'grain' as const },
    { name: 'Trứng cút', nameAscii: 'trung cut', category: 'protein' as const },
    { name: 'Cua đồng xay', nameAscii: 'cua dong xay', category: 'protein' as const, allergenTags: ['shellfish'] },
    { name: 'Khoai môn', nameAscii: 'khoai mon', category: 'vegetable' as const },
    { name: 'Cà rốt', nameAscii: 'ca rot', category: 'vegetable' as const },
  ];

  const ingredients: Record<string, string> = {};
  for (const ing of ingredientData) {
    const created = await prisma.ingredient.upsert({
      where: { name: ing.name },
      update: {},
      create: {
        name: ing.name,
        nameAscii: ing.nameAscii,
        category: ing.category,
        allergenTags: ing.allergenTags || [],
        isCommon: true,
      },
    });
    ingredients[ing.name] = created.id;
  }
  console.log(`  ✅ Ingredients: ${Object.keys(ingredients).length} items`);

  // ── 4. Recipes ────────────────────────────────────────────────
  const recipes = [
    {
      name: 'Phở bò Hà Nội',
      nameAscii: 'pho bo ha noi',
      slug: 'pho-bo-ha-noi',
      description: 'Phở bò Hà Nội truyền thống với nước dùng trong, thơm mùi quế hồi, thịt bò tái và chín, ăn kèm rau thơm.',
      cuisine: 'north' as const,
      mealTypes: ['breakfast' as const, 'dinner' as const],
      difficulty: 'medium' as const,
      cookTime: 45,
      prepTime: 15,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1701480253822-1842236c9a97?w=800',
      tags: ['Truyền thống', 'Ấm áp', 'Miền Bắc'],
      isPublished: true,
      popularityScore: 95,
      ingredients: [
        { name: 'Bánh phở tươi', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thịt bò nạm', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Xương ống bò', qty: 500, unit: 'gram', group: 'main' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Gừng', qty: 50, unit: 'gram', group: 'main' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường phèn', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Muối', qty: 1, unit: 'tsp', group: 'seasoning' as const },
        { name: 'Hành lá', qty: 1, unit: 'bó', group: 'garnish' as const },
        { name: 'Giá đỗ', qty: 100, unit: 'gram', group: 'garnish' as const },
        { name: 'Rau thơm', qty: 1, unit: 'bó', group: 'garnish' as const },
        { name: 'Chanh', qty: 2, unit: 'quả', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Sơ chế xương bò', desc: 'Rửa sạch xương ống bò dưới nước chảy. Cho xương vào nồi nước sôi, chần 5 phút để loại bỏ tạp chất. Vớt ra, rửa lại.', dur: null },
        { n: 2, title: 'Nướng hành gừng', desc: 'Nướng hành tây và gừng trực tiếp trên lửa cho đến khi vỏ cháy đen, thơm. Rửa sạch phần cháy.', dur: 10 },
        { n: 3, title: 'Hầm nước dùng', desc: 'Cho xương vào nồi lớn, đổ 3 lít nước. Thêm gừng nướng và hành tây nướng. Đun sôi, hạ lửa nhỏ, hầm 3 giờ. Hớt bọt thường xuyên.', dur: 180 },
        { n: 4, title: 'Nêm nếm', desc: 'Cho nước mắm, đường phèn, muối vào nước dùng. Nêm nếm cho vừa ăn. Lọc bỏ xương và gia vị.', dur: null },
        { n: 5, title: 'Hoàn thành', desc: 'Trụng bánh phở qua nước sôi 10 giây. Xếp bánh phở vào tô, cho thịt bò thái mỏng lên trên. Chan nước dùng nóng. Rắc hành lá, ngò gai. Ăn kèm giá đỗ, rau thơm, chanh và tương ớt.', dur: null },
      ],
      nutrition: { calories: 450, protein: 35.2, carbs: 42.8, fat: 15.3, fiber: 4.6 },
    },
    {
      name: 'Cơm tấm sườn nướng',
      nameAscii: 'com tam suon nuong',
      slug: 'com-tam-suon-nuong',
      description: 'Cơm tấm Sài Gòn chính hiệu với sườn nướng than hoa, trứng ốp la, bì và đồ chua, chan nước mắm pha ngọt.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 30,
      prepTime: 20,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1707535347953-6cf5a129d55c?w=800',
      tags: ['Comfort food', 'Miền Nam', 'Nhanh gọn'],
      isPublished: true,
      popularityScore: 92,
      ingredients: [
        { name: 'Gạo tấm', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Sườn heo', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Trứng ốp la', qty: 2, unit: 'quả', group: 'main' as const },
        { name: 'Bì heo', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Đồ chua', qty: 100, unit: 'gram', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 4, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
        { name: 'Mỡ hành', qty: 2, unit: 'tbsp', group: 'garnish' as const },
        { name: 'Dưa leo', qty: 1, unit: 'quả', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Ướp sườn', desc: 'Ướp sườn heo với nước mắm, đường, tỏi băm, tiêu. Ướp ít nhất 30 phút cho thấm.', dur: 30 },
        { n: 2, title: 'Nấu cơm tấm', desc: 'Nấu gạo tấm với tỉ lệ nước 1:1.2. Cơm tấm cần nấu hơi khô.', dur: 20 },
        { n: 3, title: 'Nướng sườn', desc: 'Nướng sườn trên bếp than hoặc chảo gang, lật đều hai mặt cho đến khi chín vàng và có mùi thơm.', dur: 15 },
        { n: 4, title: 'Hoàn thành', desc: 'Xúc cơm tấm ra đĩa, đặt sườn nướng, trứng ốp la, bì heo lên trên. Rưới mỡ hành. Ăn kèm đồ chua, dưa leo và nước mắm pha.', dur: null },
      ],
      nutrition: { calories: 550, protein: 38.5, carbs: 52.1, fat: 20.4, fiber: 2.3 },
    },
    {
      name: 'Bún bò Huế',
      nameAscii: 'bun bo hue',
      slug: 'bun-bo-hue',
      description: 'Bún bò Huế đậm đà hương vị miền Trung, nước dùng cay nồng từ sả, mắm ruốc và ớt, ăn kèm rau sống.',
      cuisine: 'central' as const,
      mealTypes: ['breakfast' as const, 'lunch' as const],
      difficulty: 'medium' as const,
      cookTime: 50,
      prepTime: 20,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1597345637412-9fd611e758f3?w=800',
      tags: ['Cay', 'Đậm đà', 'Miền Trung'],
      isPublished: true,
      popularityScore: 88,
      ingredients: [
        { name: 'Bún tươi', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thịt bò nạm', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 150, unit: 'gram', group: 'main' as const },
        { name: 'Chả cua', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Sả', qty: 3, unit: 'cây', group: 'seasoning' as const },
        { name: 'Mắm ruốc', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Ớt', qty: 4, unit: 'quả', group: 'seasoning' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Hầm xương', desc: 'Luộc xương bò qua nước sôi, rửa sạch. Hầm xương với nước trong 2 giờ.', dur: 120 },
        { n: 2, title: 'Phi sả ớt', desc: 'Phi sả băm nhỏ với dầu ăn cho thơm. Thêm mắm ruốc, ớt bột, khuấy đều.', dur: 10 },
        { n: 3, title: 'Nêm nước dùng', desc: 'Cho hỗn hợp sả ớt vào nồi nước dùng. Nêm nước mắm, muối, đường. Nấu thêm 30 phút.', dur: 30 },
        { n: 4, title: 'Hoàn thành', desc: 'Trụng bún, xếp vào tô. Xếp thịt bò, thịt heo, chả cua lên trên. Chan nước dùng nóng. Ăn kèm rau sống, giá, bắp chuối.', dur: null },
      ],
      nutrition: { calories: 580, protein: 40.1, carbs: 48.5, fat: 22.8, fiber: 5.2 },
    },
    {
      name: 'Bánh mì thịt nướng',
      nameAscii: 'banh mi thit nuong',
      slug: 'banh-mi-thit-nuong',
      description: 'Bánh mì Việt Nam giòn rụm với thịt nướng mềm, paté, đồ chua và rau thơm. Bữa sáng nhanh gọn.',
      cuisine: 'south' as const,
      mealTypes: ['breakfast' as const, 'snack' as const],
      difficulty: 'easy' as const,
      cookTime: 20,
      prepTime: 10,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1715925717150-2a6d181d8846?w=800',
      tags: ['Nhanh gọn', '< 30 phút', 'Tiện lợi'],
      isPublished: true,
      popularityScore: 90,
      ingredients: [
        { name: 'Bánh mì', qty: 2, unit: 'ổ', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Paté', qty: 50, unit: 'gram', group: 'main' as const },
        { name: 'Đồ chua', qty: 50, unit: 'gram', group: 'garnish' as const },
        { name: 'Dưa leo', qty: 1, unit: 'quả', group: 'garnish' as const },
        { name: 'Ngò', qty: 1, unit: 'bó', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tương ớt', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Ướp thịt', desc: 'Thịt ba chỉ thái mỏng, ướp nước mắm, đường, tỏi, tiêu 15 phút.', dur: 15 },
        { n: 2, title: 'Nướng thịt', desc: 'Nướng thịt trên chảo nóng hoặc than cho chín vàng.', dur: 10 },
        { n: 3, title: 'Hoàn thành', desc: 'Nướng bánh mì cho nóng giòn. Phết paté, xếp thịt nướng, đồ chua, dưa leo, ngò. Xịt tương ớt.', dur: null },
      ],
      nutrition: { calories: 420, protein: 25.3, carbs: 38.6, fat: 18.2, fiber: 3.1 },
    },
    {
      name: 'Gỏi cuốn tôm thịt',
      nameAscii: 'goi cuon tom thit',
      slug: 'goi-cuon-tom-thit',
      description: 'Gỏi cuốn tươi mát với tôm, thịt luộc, bún, rau thơm, cuốn trong bánh tráng mỏng, chấm nước mắm pha.',
      cuisine: 'south' as const,
      mealTypes: ['snack' as const, 'lunch' as const],
      difficulty: 'easy' as const,
      cookTime: 25,
      prepTime: 15,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1656945843375-207bb6e47750?w=800',
      tags: ['Healthy', 'Thanh nhẹ', 'Không dầu mỡ'],
      isPublished: true,
      popularityScore: 85,
      ingredients: [
        { name: 'Bánh tráng', qty: 12, unit: 'tấm', group: 'main' as const },
        { name: 'Tôm', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 150, unit: 'gram', group: 'main' as const },
        { name: 'Bún', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
        { name: 'Rau thơm', qty: 1, unit: 'bó', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Luộc tôm thịt', desc: 'Luộc tôm và thịt ba chỉ cho chín vừa. Tôm bóc vỏ, bổ đôi. Thịt thái lát mỏng.', dur: 15 },
        { n: 2, title: 'Chuẩn bị nhân', desc: 'Trụng bún qua nước sôi. Rửa sạch rau sống, rau thơm, để ráo nước.', dur: null },
        { n: 3, title: 'Cuốn gỏi', desc: 'Nhúng bánh tráng nhanh qua nước ấm, đặt trên mặt phẳng. Xếp rau, bún, thịt, tôm lên. Cuộn chặt tay.', dur: null },
        { n: 4, title: 'Pha nước chấm', desc: 'Pha nước mắm chua ngọt: nước mắm + nước + đường + chanh + tỏi ớt băm.', dur: null },
      ],
      nutrition: { calories: 280, protein: 22.5, carbs: 32.1, fat: 8.4, fiber: 3.8 },
    },
    {
      name: 'Mì Quảng gà',
      nameAscii: 'mi quang ga',
      slug: 'mi-quang-ga',
      description: 'Mì Quảng gà truyền thống Đà Nẵng với nước dùng sánh vàng từ nghệ, đậu phộng rang, bánh tráng nướng.',
      cuisine: 'central' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'medium' as const,
      cookTime: 40,
      prepTime: 15,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
      tags: ['Miền Trung', 'Đặc sản', 'Đà Nẵng'],
      isPublished: true,
      popularityScore: 82,
      ingredients: [
        { name: 'Mì Quảng', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thịt gà', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Tôm sú', qty: 150, unit: 'gram', group: 'main' as const },
        { name: 'Nghệ', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đậu phộng', qty: 50, unit: 'gram', group: 'garnish' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Nấu nước dùng', desc: 'Luộc gà nguyên con, giữ lại nước dùng. Xé gà thành sợi.', dur: 30 },
        { n: 2, title: 'Phi nghệ tỏi', desc: 'Phi tỏi với dầu, thêm nghệ bột, khuấy đều. Cho vào nước dùng gà.', dur: 5 },
        { n: 3, title: 'Xào nhân', desc: 'Xào tôm sú với gia vị cho chín vàng. Nêm nước mắm.', dur: 10 },
        { n: 4, title: 'Hoàn thành', desc: 'Trụng mì Quảng. Xếp vào tô, cho gà xé, tôm sú lên. Chan nước dùng vàng, rắc đậu phộng rang. Ăn kèm rau sống.', dur: null },
      ],
      nutrition: { calories: 520, protein: 42.3, carbs: 45.8, fat: 16.7, fiber: 4.1 },
    },
    // ── Quick Cook ≤15 min ──────────────────────────────────────
    {
      name: 'Trứng chiên nước mắm',
      nameAscii: 'trung chien nuoc mam',
      slug: 'trung-chien-nuoc-mam',
      description: 'Trứng chiên giòn rụm rim nước mắm chua ngọt, món ăn nhanh kiểu Việt cho bữa cơm gia đình.',
      cuisine: 'south' as const,
      mealTypes: ['breakfast' as const, 'lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 10,
      prepTime: 5,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
      tags: ['Nhanh gọn', '< 15 phút', 'Dễ làm'],
      isPublished: true,
      popularityScore: 88,
      ingredients: [
        { name: 'Trứng ốp la', qty: 4, unit: 'quả', group: 'main' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tiêu', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Chiên trứng', desc: 'Đun nóng dầu trong chảo, đập trứng vào chiên giòn cạnh, lòng đào hơi chảy.', dur: 5 },
        { n: 2, title: 'Rim nước mắm', desc: 'Pha nước mắm + đường + tiêu. Rưới lên trứng chiên, đun lửa nhỏ cho sệt.', dur: 3 },
      ],
      nutrition: { calories: 320, protein: 24, carbs: 8, fat: 22, fiber: 0 },
    },
    {
      name: 'Mì xào rau củ',
      nameAscii: 'mi xao rau cu',
      slug: 'mi-xao-rau-cu',
      description: 'Mì trứng xào nhanh với rau củ giòn, hương vị dầu hào thơm lừng, 12 phút có ngay bữa ăn.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 12,
      prepTime: 8,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=800',
      tags: ['Nhanh gọn', '< 15 phút', 'Tiện lợi'],
      isPublished: true,
      popularityScore: 84,
      ingredients: [
        { name: 'Bún tươi', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Cà chua', qty: 2, unit: 'quả', group: 'main' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Xào rau', desc: 'Phi tỏi thơm, cho rau củ vào xào lửa lớn 3 phút.', dur: 3 },
        { n: 2, title: 'Thêm mì', desc: 'Cho mì vào, nêm nước mắm, xào đều 2 phút.', dur: 2 },
      ],
      nutrition: { calories: 380, protein: 12, carbs: 52, fat: 14, fiber: 4.5 },
    },
    {
      name: 'Rau muống xào tỏi',
      nameAscii: 'rau muong xao toi',
      slug: 'rau-muong-xao-toi',
      description: 'Rau muống xào tỏi giòn ngọt, món rau quen thuộc trên mâm cơm Việt, chỉ 8 phút.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 8,
      prepTime: 5,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1543339308-d548ea3e0c22?w=800',
      tags: ['Nhanh gọn', '< 15 phút', 'Rau xanh'],
      isPublished: true,
      popularityScore: 80,
      ingredients: [
        { name: 'Rau sống', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Tỏi', qty: 5, unit: 'tép', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Phi tỏi', desc: 'Đun nóng dầu, phi tỏi băm vàng thơm.', dur: 2 },
        { n: 2, title: 'Xào rau', desc: 'Cho rau muống vào, đảo lửa lớn. Nêm nước mắm, đường. Xào 2 phút giòn xanh.', dur: 3 },
      ],
      nutrition: { calories: 120, protein: 4.5, carbs: 8.2, fat: 8, fiber: 3.6 },
    },
    {
      name: 'Trứng hấp kiểu Nhật',
      nameAscii: 'trung hap kieu nhat',
      slug: 'trung-hap-kieu-nhat',
      description: 'Trứng hấp mềm mịn kiểu chawanmushi, nhẹ nhàng cho bữa sáng hoặc ăn kèm.',
      cuisine: 'international' as const,
      mealTypes: ['breakfast' as const, 'snack' as const],
      difficulty: 'easy' as const,
      cookTime: 15,
      prepTime: 5,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800',
      tags: ['Healthy', '< 15 phút', 'Nhẹ nhàng'],
      isPublished: true,
      popularityScore: 75,
      ingredients: [
        { name: 'Trứng ốp la', qty: 3, unit: 'quả', group: 'main' as const },
        { name: 'Nước mắm', qty: 1, unit: 'tsp', group: 'seasoning' as const },
        { name: 'Hành lá', qty: 1, unit: 'cây', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Pha trứng', desc: 'Đánh trứng nhẹ nhàng, thêm nước dasia 1:1.5, lọc qua rây.', dur: 3 },
        { n: 2, title: 'Hấp', desc: 'Hấp cách thủy 12 phút, lửa nhỏ, đậy nắp hé. Rắc hành lá.', dur: 12 },
      ],
      nutrition: { calories: 180, protein: 15, carbs: 2, fat: 12, fiber: 0 },
    },
    {
      name: 'Salad bò Thái Lan',
      nameAscii: 'salad bo thai lan',
      slug: 'salad-bo-thai-lan',
      description: 'Salad bò kiểu Thái chua cay sảng khoái, thịt bò áp chảo medium, ăn kèm rau thơm.',
      cuisine: 'international' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 15,
      prepTime: 10,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
      tags: ['Healthy', '< 15 phút', 'Low carb'],
      isPublished: true,
      popularityScore: 78,
      ingredients: [
        { name: 'Thịt bò nạm', qty: 250, unit: 'gram', group: 'main' as const },
        { name: 'Cà chua', qty: 2, unit: 'quả', group: 'main' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Chanh', qty: 2, unit: 'quả', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Ớt', qty: 2, unit: 'quả', group: 'seasoning' as const },
        { name: 'Rau thơm', qty: 1, unit: 'bó', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Áp chảo bò', desc: 'Ướp bò với tiêu muối. Áp chảo lửa lớn 2 phút mỗi mặt (medium). Để nghỉ 3 phút, thái lát.', dur: 7 },
        { n: 2, title: 'Trộn salad', desc: 'Trộn bò với hành tây, cà chua, rau thơm. Pha nước trộn: nước mắm + chanh + đường + ớt. Rưới đều.', dur: 5 },
      ],
      nutrition: { calories: 350, protein: 38, carbs: 12, fat: 16, fiber: 3 },
    },
    // ── Medium recipes ──────────────────────────────────────────
    {
      name: 'Cháo gà lá gừng',
      nameAscii: 'chao ga la gung',
      slug: 'chao-ga-la-gung',
      description: 'Cháo gà nóng hổi thơm gừng, thịt gà xé tơi, ăn kèm quẩy và hành phi. Món bổ dưỡng cho cả nhà.',
      cuisine: 'north' as const,
      mealTypes: ['breakfast' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 35,
      prepTime: 10,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
      tags: ['Ấm áp', 'Bổ dưỡng', 'Miền Bắc'],
      isPublished: true,
      popularityScore: 86,
      ingredients: [
        { name: 'Thịt gà', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Gạo tấm', qty: 150, unit: 'gram', group: 'main' as const },
        { name: 'Gừng', qty: 30, unit: 'gram', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Hành lá', qty: 2, unit: 'cây', group: 'garnish' as const },
        { name: 'Tiêu', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Nấu gà', desc: 'Luộc gà nguyên con 20 phút, vớt ra xé tơi. Giữ nước dùng.', dur: 20 },
        { n: 2, title: 'Nấu cháo', desc: 'Vo gạo, cho vào nước dùng gà, thêm gừng thái sợi. Nấu nhỏ lửa đến khi nhừ.', dur: 25 },
        { n: 3, title: 'Hoàn thành', desc: 'Múc cháo ra tô, cho gà xé lên, rắc hành lá, tiêu, ít gừng thái chỉ.', dur: null },
      ],
      nutrition: { calories: 380, protein: 32, carbs: 38, fat: 10, fiber: 1.5 },
    },
    {
      name: 'Canh chua cá lóc',
      nameAscii: 'canh chua ca loc',
      slug: 'canh-chua-ca-loc',
      description: 'Canh chua miền Nam chua ngọt thanh mát, cá lóc tươi nấu với thơm, cà chua, đậu bắp, bạc hà.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 25,
      prepTime: 15,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
      tags: ['Thanh mát', 'Miền Nam', 'Healthy'],
      isPublished: true,
      popularityScore: 87,
      ingredients: [
        { name: 'Cá kho', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thơm (dứa)', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Cà chua', qty: 2, unit: 'quả', group: 'main' as const },
        { name: 'Đậu bắp', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Bạc hà', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Me', qty: 50, unit: 'gram', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Rau thơm', qty: 1, unit: 'bó', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Sơ chế', desc: 'Cá lóc làm sạch, cắt khúc. Thơm cắt miếng, cà chua bổ múi, đậu bắp cắt khúc.', dur: 10 },
        { n: 2, title: 'Nấu canh', desc: 'Đun nước sôi, cho me vào lấy nước chua. Cho thơm, cà chua vào nấu 5 phút.', dur: 5 },
        { n: 3, title: 'Hoàn thành', desc: 'Thêm cá lóc, đậu bắp, bạc hà. Nêm nước mắm, đường. Nấu thêm 5 phút. Rắc rau thơm.', dur: 5 },
      ],
      nutrition: { calories: 280, protein: 30, carbs: 18, fat: 8, fiber: 5 },
    },
    {
      name: 'Cá kho tộ',
      nameAscii: 'ca kho to',
      slug: 'ca-kho-to',
      description: 'Cá kho tộ đậm đà miền Nam, cá basa kho trong nồi đất với nước màu và tiêu, cơm trắng ăn mãi không chán.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'medium' as const,
      cookTime: 40,
      prepTime: 10,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1597345637412-9fd611e758f3?w=800',
      tags: ['Đậm đà', 'Miền Nam', 'Cơm nhà'],
      isPublished: true,
      popularityScore: 89,
      ingredients: [
        { name: 'Cá kho', qty: 500, unit: 'gram', group: 'main' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tiêu', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
        { name: 'Ớt', qty: 2, unit: 'quả', group: 'seasoning' as const },
        { name: 'Hành lá', qty: 2, unit: 'cây', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Thắng nước màu', desc: 'Cho đường vào nồi, đun nhỏ lửa đến khi thành caramel vàng nâu.', dur: 5 },
        { n: 2, title: 'Kho cá', desc: 'Xếp cá vào nồi đất, thêm nước mắm, nước, tiêu, tỏi, ớt. Kho nhỏ lửa 30 phút.', dur: 30 },
        { n: 3, title: 'Hoàn thành', desc: 'Kho đến khi nước sệt lại, rắc hành lá, tiêu. Ăn nóng với cơm trắng.', dur: null },
      ],
      nutrition: { calories: 380, protein: 35, carbs: 12, fat: 20, fiber: 0.5 },
    },
    {
      name: 'Bún chả Hà Nội',
      nameAscii: 'bun cha ha noi',
      slug: 'bun-cha-ha-noi',
      description: 'Bún chả Hà Nội với chả viên và thịt nướng thơm lừng, nước chấm chua ngọt, rau sống tươi mát.',
      cuisine: 'north' as const,
      mealTypes: ['lunch' as const],
      difficulty: 'medium' as const,
      cookTime: 30,
      prepTime: 20,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
      tags: ['Truyền thống', 'Miền Bắc', 'Nướng'],
      isPublished: true,
      popularityScore: 93,
      ingredients: [
        { name: 'Bún tươi', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Nước mắm', qty: 4, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 4, unit: 'tép', group: 'seasoning' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
        { name: 'Chanh', qty: 2, unit: 'quả', group: 'seasoning' as const },
        { name: 'Ớt', qty: 2, unit: 'quả', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Ướp thịt', desc: 'Thái ba chỉ mỏng, ướp nước mắm, đường, tỏi, tiêu. Viên thịt thành biên.', dur: 15 },
        { n: 2, title: 'Nướng chả', desc: 'Nướng thịt và chả trên than hoa hoặc chảo gang, lật đều.', dur: 15 },
        { n: 3, title: 'Pha nước chấm', desc: 'Nước mắm + nước + đường + chanh + tỏi ớt. Khuấy đều, cho thịt nướng vào.', dur: null },
        { n: 4, title: 'Hoàn thành', desc: 'Bún ra đĩa, ăn kèm chả nướng, nước chấm chua ngọt, rau sống.', dur: null },
      ],
      nutrition: { calories: 480, protein: 30, carbs: 48, fat: 18, fiber: 4 },
    },
    {
      name: 'Bún thịt nướng Sài Gòn',
      nameAscii: 'bun thit nuong sai gon',
      slug: 'bun-thit-nuong-sai-gon',
      description: 'Bún thịt nướng kiểu Sài Gòn trộn nước mắm pha, đậu phộng, hành phi, rau sống tươi mát.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 25,
      prepTime: 15,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=800',
      tags: ['Miền Nam', 'Đường phố', 'Nướng'],
      isPublished: true,
      popularityScore: 86,
      ingredients: [
        { name: 'Bún tươi', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 250, unit: 'gram', group: 'main' as const },
        { name: 'Đậu phộng', qty: 50, unit: 'gram', group: 'garnish' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
        { name: 'Chanh', qty: 1, unit: 'quả', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Ướp thịt', desc: 'Ướp thịt với sả, tỏi, nước mắm, đường, dầu ăn. Để 15 phút.', dur: 15 },
        { n: 2, title: 'Nướng', desc: 'Nướng thịt trên chảo gang hoặc than đến vàng đều.', dur: 12 },
        { n: 3, title: 'Hoàn thành', desc: 'Bún ra tô, rau sống, thịt nướng lên trên, rắc đậu phộng, hành phi. Rưới nước mắm pha.', dur: null },
      ],
      nutrition: { calories: 520, protein: 28, carbs: 55, fat: 20, fiber: 4.5 },
    },
    {
      name: 'Chè đậu xanh nước cốt dừa',
      nameAscii: 'che dau xanh nuoc cot dua',
      slug: 'che-dau-xanh',
      description: 'Chè đậu xanh bùi bùi, nước cốt dừa béo ngậy, thơm lá dứa. Món tráng miệng truyền thống.',
      cuisine: 'south' as const,
      mealTypes: ['snack' as const],
      difficulty: 'easy' as const,
      cookTime: 30,
      prepTime: 10,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
      tags: ['Tráng miệng', 'Miền Nam', 'Truyền thống'],
      isPublished: true,
      popularityScore: 77,
      ingredients: [
        { name: 'Đậu phộng', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Đường', qty: 100, unit: 'gram', group: 'seasoning' as const },
        { name: 'Muối', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Nấu đậu', desc: 'Ngâm đậu xanh 2 giờ, nấu mềm nhừ với nước.', dur: 20 },
        { n: 2, title: 'Nêm nếm', desc: 'Cho đường, chút muối. Khuấy đều. Thêm nước cốt dừa khuấy nhẹ.', dur: 5 },
      ],
      nutrition: { calories: 250, protein: 10, carbs: 42, fat: 5, fiber: 6 },
    },
    {
      name: 'Xôi xéo Hà Nội',
      nameAscii: 'xoi xeo ha noi',
      slug: 'xoi-xeo-ha-noi',
      description: 'Xôi xéo vàng ươm từ đậu xanh và nghệ, rưới hành phi giòn rụm, bữa sáng đặc trưng Hà Nội.',
      cuisine: 'north' as const,
      mealTypes: ['breakfast' as const],
      difficulty: 'medium' as const,
      cookTime: 40,
      prepTime: 30,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
      tags: ['Miền Bắc', 'Bữa sáng', 'Truyền thống'],
      isPublished: true,
      popularityScore: 79,
      ingredients: [
        { name: 'Gạo tấm', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Đậu phộng', qty: 150, unit: 'gram', group: 'main' as const },
        { name: 'Nghệ', qty: 1, unit: 'tsp', group: 'seasoning' as const },
        { name: 'Hành tây', qty: 3, unit: 'củ', group: 'garnish' as const },
        { name: 'Dầu ăn', qty: 100, unit: 'ml', group: 'seasoning' as const },
        { name: 'Muối', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Ngâm gạo', desc: 'Ngâm gạo nếp 4 giờ, trộn bột nghệ, hấp chín.', dur: 30 },
        { n: 2, title: 'Nấu nhân đậu', desc: 'Luộc đậu xanh mềm, nghiền nhuyễn, trộn đường.', dur: 15 },
        { n: 3, title: 'Phi hành', desc: 'Thái hành mỏng, phi vàng giòn trong dầu.', dur: 10 },
        { n: 4, title: 'Hoàn thành', desc: 'Xôi ra đĩa, cho nhân đậu, rưới hành phi và mỡ hành.', dur: null },
      ],
      nutrition: { calories: 450, protein: 14, carbs: 62, fat: 16, fiber: 5 },
    },
    {
      name: 'Cơm chiên dương châu',
      nameAscii: 'com chien duong chau',
      slug: 'com-chien-duong-chau',
      description: 'Cơm chiên dương châu tôm, trứng, lạp xưởng, hạt đậu Hà Lan. Bữa ăn nhanh cho cả nhà.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 15,
      prepTime: 10,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
      tags: ['Nhanh gọn', '< 15 phút', 'Dễ làm'],
      isPublished: true,
      popularityScore: 91,
      ingredients: [
        { name: 'Cơm trắng', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Tôm', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Trứng ốp la', qty: 2, unit: 'quả', group: 'main' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Nước mắm', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tiêu', qty: 1, unit: 'tsp', group: 'seasoning' as const },
        { name: 'Hành lá', qty: 2, unit: 'cây', group: 'garnish' as const },
      ],
      steps: [
        { n: 1, title: 'Chiên trứng', desc: 'Đánh trứng, chiên tơi rồi cho ra.', dur: 3 },
        { n: 2, title: 'Xào cơm', desc: 'Phi hành tỏi, xào tôm chín. Cho cơm nguội vào đảo lửa lớn, nêm nước mắm.', dur: 7 },
        { n: 3, title: 'Hoàn thành', desc: 'Trộn trứng vào cơm chiên, rắc hành lá, tiêu. Ăn nóng.', dur: null },
      ],
      nutrition: { calories: 520, protein: 22, carbs: 65, fat: 18, fiber: 2 },
    },
    {
      name: 'Bò lúc lắc',
      nameAscii: 'bo luc lac',
      slug: 'bo-luc-lac',
      description: 'Thịt bò tẩm ướp xào nhanh tay trên lửa lớn với ớt chuông và hành tây, ăn kèm cơm trắng hoặc khoai tây chiên.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'medium' as const,
      cookTime: 15,
      prepTime: 20,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1544928147-79a2dbc1f389?w=800',
      tags: ['Đậm đà', 'Thịt bò', 'Bữa tối'],
      isPublished: true,
      popularityScore: 89,
      ingredients: [
        { name: 'Thịt bò nạm', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Ớt chuông', qty: 1, unit: 'quả', group: 'main' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Sơ chế', desc: 'Thái bò thành khối vuông nhỏ. Ướp tỏi, tiêu, nước tương.', dur: 15 },
        { n: 2, title: 'Xào rau', desc: 'Xào hành tây và ớt chuông cho chín tới rồi để riêng.', dur: 5 },
        { n: 3, title: 'Lúc lắc bò', desc: 'Cho dầu vào chảo thật nóng, trút bò vào xóc đều (lúc lắc) cho xém cạnh.', dur: 5 },
        { n: 4, title: 'Hoàn thành', desc: 'Trộn rau vào bò, đảo nhanh, tắt bếp.', dur: null },
      ],
      nutrition: { calories: 450, protein: 30, carbs: 10, fat: 25, fiber: 3 },
    },
    {
      name: 'Canh khổ qua nhồi thịt',
      nameAscii: 'canh kho qua nhoi thit',
      slug: 'canh-kho-qua-nhoi-thit',
      description: 'Canh khổ qua (mướp đắng) nhồi thịt thanh mát, món ăn giải nhiệt quen thuộc của gia đình Việt, đặc biệt ngày Tết.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'medium' as const,
      cookTime: 30,
      prepTime: 20,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1620063234971-ce4cd1951f25?w=800',
      tags: ['Thanh mát', 'Giải nhiệt', 'Truyền thống'],
      isPublished: true,
      popularityScore: 85,
      ingredients: [
        { name: 'Khổ qua', qty: 3, unit: 'quả', group: 'main' as const },
        { name: 'Thịt heo xay', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Nấm mèo', qty: 20, unit: 'gram', group: 'main' as const },
        { name: 'Miến', qty: 20, unit: 'gram', group: 'main' as const },
        { name: 'Hành lá', qty: 2, unit: 'cây', group: 'garnish' as const },
        { name: 'Nước mắm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Tiêu', qty: 1, unit: 'tsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Làm nhân', desc: 'Ngâm mềm nấm và miến rồi băm nhỏ. Trộn đều với thịt heo, hành, tiêu, nước mắm.', dur: 15 },
        { n: 2, title: 'Sơ chế khổ qua', desc: 'Cắt dưa làm đôi hoặc moi ruột, nhồi chặt nhân vào trong.', dur: 5 },
        { n: 3, title: 'Nấu canh', desc: 'Đun sôi nước, thả khổ qua vào hầm với lửa vừa khoảng 30 phút cho mềm.', dur: 30 },
      ],
      nutrition: { calories: 250, protein: 18, carbs: 15, fat: 12, fiber: 5 },
    },
    {
      name: 'Bánh xèo miền Tây',
      nameAscii: 'banh xeo mien tay',
      slug: 'banh-xeo-mien-tay',
      description: 'Bánh xèo giòn rụm với nhân tôm, thịt, giá đỗ, cuộn cùng bánh tráng và rau rừng, chấm nước mắm chua ngọt.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'hard' as const,
      cookTime: 25,
      prepTime: 30,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1599354026600-98308ce7a52f?w=800',
      tags: ['Cuộn', 'Miền Tây', 'Truyền thống'],
      isPublished: true,
      popularityScore: 94,
      ingredients: [
        { name: 'Bột bánh xèo', qty: 500, unit: 'gram', group: 'main' as const },
        { name: 'Tôm', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Giá đỗ', qty: 150, unit: 'gram', group: 'garnish' as const },
        { name: 'Rau sống', qty: 300, unit: 'gram', group: 'garnish' as const },
        { name: 'Dầu ăn', qty: 5, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Pha bột', desc: 'Pha bột bánh xèo với nước và cốt dừa theo tỉ lệ trên bao bì, thêm hành lá thái nhỏ.', dur: 5 },
        { n: 2, title: 'Xào nhân', desc: 'Xào tôm và thịt ba chỉ cho chín.', dur: 10 },
        { n: 3, title: 'Đổ bánh', desc: 'Tráng một lớp bột mỏng trên chảo nóng, thêm nhân và giá đỗ, đậy nắp 2 phút rồi gập đôi bánh.', dur: 10 },
        { n: 4, title: 'Hoàn thành', desc: 'Dùng bánh tráng cuộn bánh xèo với rau sống, chấm nước mắm chua ngọt.', dur: null },
      ],
      nutrition: { calories: 480, protein: 20, carbs: 55, fat: 22, fiber: 4 },
    },
    {
      name: 'Bún riêu cua',
      nameAscii: 'bun rieu cua',
      slug: 'bun-rieu-cua',
      description: 'Bún riêu cua đồng thanh mát, ngọt nước cua, chua dịu vị cà chua và giấm bỗng, đậu hũ chiên.',
      cuisine: 'north' as const,
      mealTypes: ['breakfast' as const, 'lunch' as const],
      difficulty: 'medium' as const,
      cookTime: 40,
      prepTime: 20,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1632514332467-f4e9104085f1?w=800',
      tags: ['Nước dùng', 'Cua đồng', 'Miền Bắc'],
      isPublished: true,
      popularityScore: 89,
      ingredients: [
        { name: 'Bún tươi', qty: 500, unit: 'gram', group: 'main' as const },
        { name: 'Cua đồng xay', qty: 400, unit: 'gram', group: 'main' as const },
        { name: 'Cà chua', qty: 3, unit: 'quả', group: 'main' as const },
        { name: 'Đậu hũ', qty: 2, unit: 'miếng', group: 'main' as const },
        { name: 'Rau sống', qty: 200, unit: 'gram', group: 'garnish' as const },
        { name: 'Mắm tôm', qty: 1, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Dầu ăn', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Lọc cua', desc: 'Khuấy đều cua xay với nước, lọc lấy nước cốt. Hớt lấy phần cái đun nhỏ lửa để đóng tảng.', dur: 15 },
        { n: 2, title: 'Chiên đậu', desc: 'Cắt đậu hũ thành miếng vừa ăn, chiên vàng đều.', dur: 10 },
        { n: 3, title: 'Nấu nước dùng', desc: 'Xào xốt cà chua, cho vào nồi nước cua, thêm giấm bỗng, nếm gia vị và mắm tôm.', dur: 15 },
        { n: 4, title: 'Hoàn thành', desc: 'Cho bún vào bát, múc riêu cua, đậu hũ, chan nước. Ăn kèm rau sống.', dur: null },
      ],
      nutrition: { calories: 410, protein: 25, carbs: 55, fat: 10, fiber: 6 },
    },
    {
      name: 'Chả giò (Nem rán)',
      nameAscii: 'cha gio',
      slug: 'cha-gio-nem-ran',
      description: 'Chả giò chiên giòn rụm với nhân thịt heo, khoai môn, mộc nhĩ, tôm... Món khai vị không thể thiếu.',
      cuisine: 'south' as const,
      mealTypes: ['snack' as const, 'lunch' as const],
      difficulty: 'medium' as const,
      cookTime: 20,
      prepTime: 30,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1594916894086-6ecf52b6d1b7?w=800',
      tags: ['Chiên', 'Giòn rụm', 'Truyền thống'],
      isPublished: true,
      popularityScore: 92,
      ingredients: [
        { name: 'Bánh tráng', qty: 20, unit: 'cái', group: 'main' as const },
        { name: 'Thịt heo xay', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Trứng ốp la', qty: 1, unit: 'quả', group: 'main' as const },
        { name: 'Khoai môn', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Nấm mèo', qty: 20, unit: 'gram', group: 'main' as const },
        { name: 'Cà rốt', qty: 1, unit: 'củ', group: 'main' as const },
        { name: 'Dầu ăn', qty: 100, unit: 'ml', group: 'seasoning' as const },
        { name: 'Hành tây', qty: 1, unit: 'củ', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Làm nhân', desc: 'Cà rốt, khoai môn bào sợi. Nấm mèo ngâm mềm thái sợi. Trộn với thịt xây, trứng, gia vị.', dur: 20 },
        { n: 2, title: 'Cuốn chả', desc: 'Trải bánh tráng, cho một lượng nhân vừa phải, cuộn tròn chắc tay.', dur: 10 },
        { n: 3, title: 'Chiên chả', desc: 'Chiên ngập dầu ở lửa vừa đến khi bánh tráng vàng ươm, giòn rụm.', dur: 20 },
      ],
      nutrition: { calories: 350, protein: 12, carbs: 20, fat: 25, fiber: 3 },
    },
    {
      name: 'Gà kho sả ớt',
      nameAscii: 'ga kho sa ot',
      slug: 'ga-kho-sa-ot',
      description: 'Gà kho đậm đà, thơm lừng vị sả và cay nồng cua ớt, ăn rất tốn cơm.',
      cuisine: 'south' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 25,
      prepTime: 15,
      servings: 4,
      imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
      tags: ['Đậm đà', 'Cay nồng', 'Thịt gà'],
      isPublished: true,
      popularityScore: 88,
      ingredients: [
        { name: 'Thịt gà', qty: 500, unit: 'gram', group: 'main' as const },
        { name: 'Sả', qty: 3, unit: 'nhánh', group: 'seasoning' as const },
        { name: 'Ớt', qty: 2, unit: 'quả', group: 'seasoning' as const },
        { name: 'Tỏi', qty: 3, unit: 'tép', group: 'seasoning' as const },
        { name: 'Nước mắm', qty: 3, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Đường', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Ướp gà', desc: 'Chặt gà vừa ăn, ướp với sả, ớt băm, tỏi, nước mắm, đường trong 15 phút.', dur: 15 },
        { n: 2, title: 'Thắng nước màu', desc: 'Làm nóng dầu, thêm 1 ít đường để tạo màu.', dur: 3 },
        { n: 3, title: 'Kho gà', desc: 'Cho gà vào xào săn lại, thêm xíu nước ấm rồi đun nhỏ lửa đến khi sệt.', dur: 20 },
      ],
      nutrition: { calories: 300, protein: 28, carbs: 10, fat: 15, fiber: 1 },
    },
    {
      name: 'Bún đậu mắm tôm',
      nameAscii: 'bun dau mam tom',
      slug: 'bun-dau-mam-tom',
      description: 'Mẹt bún đậu dân dã với bún lá, đậu hũ chiên giòn, thịt luộc, chả cốm và linh hồn là chén mắm tôm đánh bông sủi bọt.',
      cuisine: 'north' as const,
      mealTypes: ['lunch' as const, 'dinner' as const],
      difficulty: 'easy' as const,
      cookTime: 20,
      prepTime: 15,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1626200419131-0bbff1df7f5e?w=800',
      tags: ['Đường phố', 'Miền Bắc', 'Mắm tôm'],
      isPublished: true,
      popularityScore: 90,
      ingredients: [
        { name: 'Bún tươi', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Đậu hũ', qty: 3, unit: 'miếng', group: 'main' as const },
        { name: 'Thịt ba chỉ', qty: 200, unit: 'gram', group: 'main' as const },
        { name: 'Chả cốm', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Rau sống', qty: 100, unit: 'gram', group: 'garnish' as const },
        { name: 'Mắm tôm', qty: 2, unit: 'tbsp', group: 'seasoning' as const },
        { name: 'Chanh', qty: 1, unit: 'quả', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Chiên đậu chả', desc: 'Cắt đậu hũ miếng vuông, chiên giòn 4 mặt. Chiên chả cốm cho vàng.', dur: 15 },
        { n: 2, title: 'Luộc thịt', desc: 'Luộc chín thịt ba chỉ, vớt ra ngâm nước đá cho giòn, thái phiến mỏng.', dur: 15 },
        { n: 3, title: 'Pha mắm tôm', desc: 'Mắm tôm thêm chút đường, vắt chanh, đánh bông bọt lên, thêm ớt thái.', dur: 2 },
        { n: 4, title: 'Hoàn thành', desc: 'Xếp bún, đậu, thịt, chả ra mẹt, ăn kèm tía tô, kinh giới.', dur: null },
      ],
      nutrition: { calories: 600, protein: 35, carbs: 60, fat: 25, fiber: 5 },
    },
    {
      name: 'Hủ tiếu Nam Vang',
      nameAscii: 'hu tieu nam vang',
      slug: 'hu-tieu-nam-vang',
      description: 'Nước lèo thanh ngọt từ xương, tôm, gan, trứng cút tỏi phi... món ăn sáng đa dạng mùi vị đặc trưng của người Hoa-Miên ở Nam Bộ.',
      cuisine: 'south' as const,
      mealTypes: ['breakfast' as const],
      difficulty: 'medium' as const,
      cookTime: 45,
      prepTime: 20,
      servings: 2,
      imageUrl: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?w=800',
      tags: ['Hủ tiếu', 'Nước dùng', 'Bữa sáng'],
      isPublished: true,
      popularityScore: 87,
      ingredients: [
        { name: 'Hủ tiếu', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Thịt heo xay', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Sườn heo', qty: 300, unit: 'gram', group: 'main' as const },
        { name: 'Tôm', qty: 100, unit: 'gram', group: 'main' as const },
        { name: 'Trứng cút', qty: 6, unit: 'quả', group: 'main' as const },
        { name: 'Giá đỗ', qty: 100, unit: 'gram', group: 'garnish' as const },
        { name: 'Tỏi', qty: 5, unit: 'tép', group: 'seasoning' as const },
      ],
      steps: [
        { n: 1, title: 'Hầm xương', desc: 'Xương hầm 1.5 tiếng lấy nước lèo thanh, nêm thêm đường phèn.', dur: 90 },
        { n: 2, title: 'Xào thịt băm', desc: 'Thịt xay xào chín với chút dầu và nước tương.', dur: 5 },
        { n: 3, title: 'Luộc nhân', desc: 'Luộc chín tôm, bóc vỏ. Luộc trứng cút bóc vỏ.', dur: 10 },
        { n: 4, title: 'Pha chế tỏi phi', desc: 'Băm nhuyễn tỏi, phi vàng trong dầu.', dur: 5 },
        { n: 5, title: 'Hoàn thành', desc: 'Trụng hủ tiếu dai, cho thịt xay, tôm, trứng cút lên, rưới tỏi phi, chan nước lèo nóng.', dur: null },
      ],
      nutrition: { calories: 500, protein: 30, carbs: 65, fat: 12, fiber: 3 },
    }
  ];

  for (const r of recipes) {
    // Create recipe
    const recipe = await prisma.recipe.upsert({
      where: { slug: r.slug },
      update: {
        name: r.name,
        imageUrl: r.imageUrl,
        isPublished: r.isPublished,
        popularityScore: r.popularityScore,
      },
      create: {
        name: r.name,
        nameAscii: r.nameAscii,
        slug: r.slug,
        description: r.description,
        cuisine: r.cuisine,
        mealTypes: r.mealTypes,
        difficulty: r.difficulty,
        cookTime: r.cookTime,
        prepTime: r.prepTime,
        servings: r.servings,
        imageUrl: r.imageUrl,
        tags: r.tags,
        isPublished: r.isPublished,
        popularityScore: r.popularityScore,
      },
    });

    // Create ingredients
    for (let i = 0; i < r.ingredients.length; i++) {
      const ing = r.ingredients[i];
      const ingredientId = ingredients[ing.name];
      if (!ingredientId) {
        console.warn(`    ⚠ Ingredient not found: ${ing.name}`);
        continue;
      }
      await prisma.recipeIngredient.upsert({
        where: { recipeId_ingredientId: { recipeId: recipe.id, ingredientId } },
        update: {},
        create: {
          recipeId: recipe.id,
          ingredientId,
          quantity: ing.qty,
          unit: ing.unit,
          groupType: ing.group,
          sortOrder: i + 1,
        },
      });
    }

    // Create steps
    for (const step of r.steps) {
      await prisma.recipeStep.upsert({
        where: { recipeId_stepNumber: { recipeId: recipe.id, stepNumber: step.n } },
        update: {},
        create: {
          recipeId: recipe.id,
          stepNumber: step.n,
          description: `**${step.title}** — ${step.desc}`,
          durationMinutes: step.dur,
        },
      });
    }

    // Create nutrition info
    await prisma.nutritionInfo.upsert({
      where: { recipeId: recipe.id },
      update: {},
      create: {
        recipeId: recipe.id,
        calories: r.nutrition.calories,
        protein: r.nutrition.protein,
        carbs: r.nutrition.carbs,
        fat: r.nutrition.fat,
        fiber: r.nutrition.fiber,
      },
    });

    console.log(`  ✅ Recipe: ${r.name}`);
  }

  // ── 5. Demo Bookmark ──────────────────────────────────────────
  const phoRecipe = await prisma.recipe.findUnique({ where: { slug: 'pho-bo-ha-noi' } });
  if (phoRecipe) {
    await prisma.bookmark.upsert({
      where: { userId_recipeId: { userId: user.id, recipeId: phoRecipe.id } },
      update: {},
      create: { userId: user.id, recipeId: phoRecipe.id },
    });
    console.log('  ✅ Bookmark: Phở bò');
  }

  console.log('\n🎉 Seed completed!');
  console.log('   Demo account: demo@mealmind.vn / Demo@1234\n');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
